name: Check and Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 检查 HTML 语法
        # 使用官方推荐的最新稳定版本标签
        uses: htmlhint/htmlhint-action@v2.0.1
        with:
          # 检查根目录下所有的 html 文件
          source: .

  deploy-site:
    runs-on: ubuntu-latest
    needs: check-code
    steps:
      - uses: actions/checkout@v4

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./